spring:
  application:
    name: order2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.180/SpringCloud_Shell?characterEncoding=utf-8&useSSL=false
    username: root
    password: '000000'
  jpa:
    show-sql: true
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
env:
  test7
girl:
  name: lili
  age: 20